apps/core/urls.py
from django.urls import path
from .views import (
                    IndexView,
                    ConfigugrationView,
                    StatisticsView,
                    TaxListView,
                    ManageTaxHtmx,
                    TaxDeleteHTMX,
                    LeadSourceListView,
                    ManageLeadSourceHtmx,
                    LeadSourceDeleteHTMX,
                    PotentialListView,
                    ManagePotentialHtmx,
                    PotentialDeleteHTMX,
                    set_language,
                )


app_name = "core"


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("configuration", ConfigugrationView.as_view(), name="configuration"),
    path("set_language/<str:language>/", set_language, name="set_language"),
    path("statistics/", StatisticsView.as_view(), name="statistics"),
    # # tax---------------------------------------------------------------
    path("taxes/", TaxListView.as_view(), name="list_tax"),
    path("taxes/create", ManageTaxHtmx.as_view(), name="create_tax"),
    path("taxes/update/<int:pk>", ManageTaxHtmx.as_view(), name="update_tax"),
    path("taxes/delete/<int:pk>", TaxDeleteHTMX.as_view(), name="delete_tax"),
    path("source_leads/", LeadSourceListView.as_view(), name="list_leadsource"),
    path(
        "source_leads/create/",
        ManageLeadSourceHtmx.as_view(),
        name="create_leadsource",
    ),
    path(
        "source_leads/update/<int:pk>",
        ManageLeadSourceHtmx.as_view(),
        name="update_leadsource",
    ),
    path(
        "source_leads/delete/<int:pk>",
        LeadSourceDeleteHTMX.as_view(),
        name="delete_leadsource",
    ),
    # # Potentiel---------------------------------------------------------------
    path("potentials/", PotentialListView.as_view(), name="list_potential"),
    path("potentials/create", ManagePotentialHtmx.as_view(), name="create_potential"),
    path(
        "potentials/update/<int:pk>",
        ManagePotentialHtmx.as_view(),
        name="update_potential",
    ),
    path(
        "potentials/delete/<int:pk>",
        PotentialDeleteHTMX.as_view(),
        name="delete_potential",
    ),
]

apps/crm/urls.py
from django.urls import path
from apps.crm.views import (
    ContactListView,
    ManageContactHTMX,
    DeleteContact,
    DeleteBulkContacts,
    ImportContacts,
    ExportContacts,
    ContactDetailView,
    ImportFieldsContact,
    CompanyListView,
    CompanyFinancialInfo,
    ManageCompanyHTMX,
    DeleteCompany,
    ImportCompanies,
    ImportFieldsCompanies,
    ExportCompanies,
    DeleteBulkCompanies,
    CompanyDetailView,
    CompanyChartView,
    CompanyContactsTable,
    ManageCompanyDocumentHTMX,
    DeleteCompanyDocument,
    ActivitySectorListView,
    ManageActivitySectorHTMX,
    DeleteActivitySector,
    ManagePublicForm,
    thank_you_view,
)

app_name = "crm"

urlpatterns = [
    ########## CONTACT #############
    path("contacts/", ContactListView.as_view(), name="list_contact"),
    path("contacts/create/", ManageContactHTMX.as_view(), name="create_contact"),
    path(
        "contacts/update/<int:pk>/", ManageContactHTMX.as_view(), name="update_contact"
    ),
    ##contact for company
    path(
        "contacts/company_contacts/<int:company_pk>/",
        ManageContactHTMX.as_view(),
        name="create_company_contacts",
    ),
    path("contacts/delete/<int:pk>/", DeleteContact.as_view(), name="delete_contact"),
    path(
        "contacts/bulk-delete/",
        DeleteBulkContacts.as_view(),
        name="bulk_delete_contacts",
    ),
    path("contacts/import/", ImportContacts.as_view(), name="import_contact"),
    path("contacts/export/", ExportContacts.as_view(), name="export_contact"),
    path("contacts/<int:pk>/", ContactDetailView.as_view(), name="detail_contact"),
    path(
        "contacts/import-fields/",
        ImportFieldsContact.as_view(),
        name="import_fields_contact",
    ),
    ########## COMPANY #############
    path("companies/", CompanyListView.as_view(), name="list_company"),
    path("companies/create/", ManageCompanyHTMX.as_view(), name="create_company"),
    path(
        "companies/update/company_financial/<int:pk>/",
        CompanyFinancialInfo.as_view(),
        name="update_company_financial",
    ),
    path(
        "companies/update/<int:pk>/", ManageCompanyHTMX.as_view(), name="update_company"
    ),
    path("companies/delete/<int:pk>/", DeleteCompany.as_view(), name="delete_company"),
    path("companies/import/", ImportCompanies.as_view(), name="import_company"),
    path(
        "companies/import-fields/",
        ImportFieldsCompanies.as_view(),
        name="import_fields_company",
    ),
    path("companies/export/", ExportCompanies.as_view(), name="export_company"),
    path(
        "companies/bulk-delete/",
        DeleteBulkCompanies.as_view(),
        name="bulk_delete_companies",
    ),
    path(
        "companies/detail/<int:pk>/", CompanyDetailView.as_view(), name="detail_company"
    ),
    path(
        "companies/detail/charts/<int:pk>/",
        CompanyChartView.as_view(),
        name="charts_company",
    ),
    path(
        "companies/company_contacts/<int:pk>/",
        CompanyContactsTable.as_view(),
        name="company_contacts",
    ),
    ######## document #############
    path(
        "companies/create_companydocument/<int:company_pk>/",
        ManageCompanyDocumentHTMX.as_view(),
        name="create_companydocument",
    ),
    path(
        "companies/document/<int:pk>/delete/",
        DeleteCompanyDocument.as_view(),
        name="delete_companydocument",
    ),
    ################ Activity Sector #############
    path(
        "activity-sectors/",
        ActivitySectorListView.as_view(),
        name="list_activitysector",
    ),
    path(
        "activity-sectors/create/",
        ManageActivitySectorHTMX.as_view(),
        name="create_activitysector",
    ),
    path(
        "activity-sectors/update/<int:pk>/",
        ManageActivitySectorHTMX.as_view(),
        name="update_activitysector",
    ),
    path(
        "activity-sectors/delete/<int:pk>/",
        DeleteActivitySector.as_view(),
        name="delete_activitysector",
    ),
    path(
        "public-forms/",
        ManagePublicForm.as_view(),
        name="public_forms_url",
    ),
    path('thank_you/', thank_you_view, name='thank_you_view'),

]

apps/tags/urls.py
from django.urls import path

from apps.tags.views import TagsListView,ManageSalleHtmx,SalleDeleteHTMX

app_name = "tags"


urlpatterns = [
    path("tags/", TagsListView.as_view(), name="list_tags"),
    path("tags/create/", ManageSalleHtmx.as_view(), name="create_tags"),
    path("tags/<int:pk>/", ManageSalleHtmx.as_view(), name="update_tags"),
    path("tags/<int:pk>/delete/", SalleDeleteHTMX.as_view(), name="delete_tags"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

# sitemaps = {
#     'terms': TermsSitemap,
#     'faq': FAQSitemap,
#     'static': StaticSitemap
# }
urlpatterns = [
    # path('markdownx/', include('markdownx.urls')),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("apps.core.urls")),
    path("", include("apps.transactions.urls")),
    path("", include("apps.crm.urls")),
    path("", include("apps.users.urls")),
    path("", include("apps.wilayas.urls")),
    path("", include("apps.leads.urls")),
    path("", include("apps.billing.urls")),
    path("", include("apps.business.urls")),
    path("", include("apps.notification.urls")),
    path("", include("apps.appointment.urls")),
    path("", include("apps.subscription.urls")),
    path("", include("apps.tags.urls")),
    
    path('tinymce/', include('tinymce.urls')),

    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
] + debug_toolbar_urls()


if settings.DEBUG:
    # import debug_toolbar
    urlpatterns += [
        path("admin/", admin.site.urls),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += path('__debug__/', include("debug_toolbar.urls")),

apps/core/forms.py
from django import forms
from apps.core.models import LeadSource, Potential, Tax


class TaxModelForm(forms.ModelForm):

    class Meta:
        fields = ("name", "tax", "is_active")
        model = Tax


class LeadSourceModelForm(forms.ModelForm):

    class Meta:
        fields = ("name",)
        model = LeadSource


class PotentialModelForm(forms.ModelForm):

    class Meta:
        fields = (
            "segment",
            "min_employees",
            "max_employees",
            "potentiel",
        )
        model = Potential
        help_texts = {
            "segment": "Lettre de segmentation (A, B, C..etc)",
            "min_employees": "Nombre minimum d'employés pour ce potentiel",
            "max_employees": "Nombre maximum d'employés pour ce potentiel",
            "potentiel": "Objectif commercial annuel de l'entreprise.",
        }

apps/core/views.py
import logging
from decimal import Decimal

from django.conf import settings
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Sum
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import translation
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView
from django_filters.views import FilterView
from django_tables2 import SingleTableMixin

from apps.billing.models import Invoice
from apps.core.mixins import BaseManageHtmxFormView, DeleteMixinHTMX
from apps.core.models import LeadSource, Potential, Tax
from apps.transactions.models import (
    ClientPayment,
    MiscTransaction,
    StaffPayment,
)

from .forms import LeadSourceModelForm, PotentialModelForm, TaxModelForm
from .tables import LeadSourceHTMxTable, PotentialHTMxTable, TaxHTMxTable

logger = logging.getLogger(__name__)


def set_language(request, language="fr"):
    lang_code = language
    translation.activate(lang_code)
    request.session[settings.LANGUAGE_SESSION_KEY] = lang_code
    request.user.language = lang_code
    request.user.save()

    response = HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    response.set_cookie(settings.LANGUAGE_COOKIE_NAME, lang_code)
    return response


class IndexView(TemplateView):
    template_name = "tables/table_partial.html"
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["size_class"] = "modal-lg mw-850px"
        # context["ledger_table"]= LedgerEntryTable(data=LedgerEntry.objects.filter(date=date.today()))
        return context

    def get_template_names(self) -> list[str]:
        if self.request.htmx:
            return ["tables/table_partial.html"]
        else:
            return ["index.html"]


# ----------------------------------Configuration----------------------------------


class ConfigugrationView(
    TemplateView
):  # this is a generic view  thazt doens't have a mode lso we do a breadcrumb manually
    template_name = "configuration/configuration.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = _("Configuration")
        context["title"] = _("Configuration")
        context["parent_url"] = reverse("core:configuration")
        return context


# ----------------------------------TAX----------------------------------


class ManageTaxHtmx(BaseManageHtmxFormView):
    form_class = TaxModelForm
    model = Tax
    hx_triggers = {
        "closeModal": "kt_modal",
        "refresh_table": None,
    }


class TaxDeleteHTMX(DeleteMixinHTMX):
    model = Tax


class TaxListView(PermissionRequiredMixin, SingleTableMixin, FilterView):
    permission_required = "core.view_tax"
    model = Tax

    template_name = "tables/table_partial.html"
    filterset_class = None
    table_class = TaxHTMxTable

    def get_queryset(self):
        return Tax.objects.all().order_by("name")


class ManageLeadSourceHtmx(BaseManageHtmxFormView):
    form_class = LeadSourceModelForm
    model = LeadSource
    hx_triggers = {
        "closeModal": "kt_modal",
        "refresh_table": None,
    }


class LeadSourceDeleteHTMX(DeleteMixinHTMX):
    model = LeadSource


class LeadSourceListView(PermissionRequiredMixin, SingleTableMixin, FilterView):
    permission_required = "core.view_leadsource"
    model = LeadSource

    template_name = "tables/table_partial.html"
    filterset_class = None  # Define your filterset class if needed
    table_class = LeadSourceHTMxTable  # Define your table class if needed

    def get_queryset(self):
        return LeadSource.objects.all().order_by("name")


# ----------------------------------Potential----------------------------------


class ManagePotentialHtmx(BaseManageHtmxFormView):
    permission_required = "core.add_potential"
    form_class = PotentialModelForm
    model = Potential
    hx_triggers = {
        "closeModal": "kt_modal",
        "refresh_table": None,
    }


class PotentialDeleteHTMX(DeleteMixinHTMX):
    permission_required = "core.delete_potential"
    model = Potential


class PotentialListView(PermissionRequiredMixin, SingleTableMixin, FilterView):
    permission_required = "core.view_potential"
    model = Potential

    template_name = "tables/table_partial.html"
    filterset_class = None  # Define your filterset class if needed
    table_class = PotentialHTMxTable  # Define your table class if needed

    def get_queryset(self):
        return Potential.objects.all()


class StatisticsView(PermissionRequiredMixin, TemplateView):
    permission_required = "transactions.can_view_statistique"
    template_name = "statistics.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_income_invoices = (
            ClientPayment.objects.aggregate(total_income=Sum("amount"))["total_income"]
            or 0
        )
        total_income_misc = (
            MiscTransaction.objects.filter(transaction_type="income").aggregate(
                total_income=Sum("amount")
            )["total_income"]
            or 0
        )
        total_income = total_income_invoices + total_income_misc
        context["total_income"] = total_income

        total_expence_staff = (
            StaffPayment.objects.aggregate(total_payment=Sum("amount"))["total_payment"]
            or 0
        )
        total_expence_misc = (
            MiscTransaction.objects.filter(transaction_type="expense").aggregate(
                total_expense=Sum("amount")
            )["total_expense"]
            or 0
        )
        total_expence = total_expence_staff + total_expence_misc
        context["total_expence"] = total_expence

        invoice_reste = sum(
            (inv.rest_amount for inv in Invoice.objects.all()), Decimal("0")
        )
        context["invoice_reste"] = invoice_reste
        print(f"invoice_reste----------->>>>: {invoice_reste}")

        return context

apps/core/templates/configuration/configuration.html
{% extends "layout/base.html" %}
{% block content %}
<div class="d-block d-md-flex justify-content-between align-items-end mb-4">
    {% include 'snippets/_breadcrumb.html' %}
</div>

<div class="row">
  <div class="col-12 col-md-3 mb-4 mb-md-0">
      <div class="card h-100 shadow-sm">
          <div class="card-header py-3">
              <h5 class="mb-0 fw-semibold">{% translate "Configuration" %}</h5>
          </div>
            <div class="list-group list-group-flush small" id="config-nav" role="tablist" style="max-height:70vh;overflow:auto">


              {% if perms.core.view_leadsource %}
              <a class="list-group-item list-group-item-action d-flex align-items-center text-black fs-5"
                 data-bs-toggle="tab" href="#source-pane" role="tab">
                 <i class="ki-outline ki-filter-search fs-2x me-2"></i> {% translate "Source de l'opportunité" %}
              </a>
              {% endif %}
              {% if perms.core.view_tax %}
              <a class="list-group-item list-group-item-action d-flex align-items-center text-black fs-5"
                 data-bs-toggle="tab" href="#tax-pane" role="tab">
                 <i class="ki-outline ki-discount fs-2x me-2"></i> {% translate "Taxe" %}
              </a>
              {% endif %}
              {% if perms.core.view_potential %}
              <a class="list-group-item list-group-item-action d-flex align-items-center text-black fs-5"
                 data-bs-toggle="tab" href="#potential-pane" role="tab">
                 <i class="ki-outline ki-graph-up fs-2x me-2"></i> {% translate "Potentiel" %}
              </a>
              {% endif %}
            
             
              {% if perms.crm.view_activitysector %}
                <a class="list-group-item list-group-item-action d-flex align-items-center text-black fs-5"
                    data-bs-toggle="tab" href="#activitysector-pane" role="tab">
                    <i class="ki-outline ki-data fs-2x me-2"></i> {% translate "Secteur d'activité" %}
                </a>
              {% endif %}
              {% if perms.tags.view_tags %}
                <a class="list-group-item list-group-item-action d-flex align-items-center text-black fs-5"
                    data-bs-toggle="tab" href="#tags-pane" role="tab">
                    <i class="ki-outline ki-flag fs-2x me-2"></i> {% translate "Tags" %}
                </a>
              {% endif %}
            </div>
      </div>
  </div>
  <div class="col-12 col-md-9">
      <div class="card shadow-sm">
          <div class="card-body tab-content" id="config-content">

             

              <div class="tab-pane fade" id="source-pane" role="tabpanel">
                  {% if perms.core.view_leadsource %}
                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <h3 class="mb-0 fw-bold">{% translate "Source de l'opportunité" %}</h3>
                        {% if perms.core.add_leadsource %}
                            <a href="#" class="btn btn-sm btn-primary"
                            data-bs-toggle="modal"
                            data-bs-target="#kt_modal"
                            hx-get="{% url 'core:create_leadsource' %}"
                            hx-target="#kt_modal_content"
                            hx-swap="innerHTML">
                            <i class="ki-duotone ki-plus fs-2"></i> {% trans 'Ajouter' %}
                            </a>
                        {% endif %}
                    </div>
                    <div id="SourceTable" class="table-responsive bg-white"
                        hx-get="{% url 'core:list_leadsource' %}"
                        hx-trigger="refresh_table from:body, revealed"
                        hx-target="#SourceTable"
                        hx-swap="innerHTML">
                    </div>
                  {% endif %}
              </div>

              <div class="tab-pane fade" id="tax-pane" role="tabpanel">
                  {% if perms.core.view_tax %}
                  <div class="d-flex justify-content-between align-items-center mb-4">
                      <h3 class="mb-0 fw-bold">{% translate "Taxe" %}</h3>
                      {% if perms.core.add_tax %}
                        <a href="#" class="btn btn-sm btn-primary"
                           data-bs-toggle="modal"
                           data-bs-target="#kt_modal"
                           hx-get="{% url 'core:create_tax' %}"
                           hx-target="#kt_modal_content"
                           hx-swap="innerHTML">
                           <i class="ki-duotone ki-plus fs-2"></i> {% trans 'Ajouter' %}
                        </a>
                      {% endif %}
                  </div>
                  <div id="TaxTable" class="table-responsive bg-white"
                       hx-get="{% url 'core:list_tax' %}"
                       hx-trigger="refresh_table from:body, revealed"
                       hx-target="#TaxTable"
                       hx-swap="innerHTML"></div>
                  {% endif %}
              </div>

              <div class="tab-pane fade" id="potential-pane" role="tabpanel">
                  {% if perms.core.view_potential %}
                  <div class="d-flex justify-content-between align-items-center mb-4">
                      <h3 class="mb-0 fw-bold">{% translate "Potentiel" %}</h3>
                      {% if perms.core.add_potential %}
                        <a href="#" class="btn btn-sm btn-primary"
                           data-bs-toggle="modal"
                           data-bs-target="#kt_modal"
                           hx-get="{% url 'core:create_potential' %}"
                           hx-target="#kt_modal_content"
                           hx-swap="innerHTML">
                           <i class="ki-duotone ki-plus fs-2"></i> {% trans 'Ajouter' %}
                        </a>

                      {% endif %}
                  </div>
                  <div id="PotentialTable" class="table-responsive bg-white"
                       hx-get="{% url 'core:list_potential' %}"
                       hx-trigger="refresh_table from:body, revealed"
                       hx-target="#PotentialTable"
                       hx-swap="innerHTML"></div>
                  {% endif %}
              </div>

             

              <div class="tab-pane fade" id="activitysector-pane" role="tabpanel">
                  {% if perms.crm.view_activitysector %}
                  <div class="d-flex justify-content-between align-items-center mb-4">
                      <h3 class="mb-0 fw-bold">{% translate "Secteur d'activité" %}</h3>
                      {% if perms.crm.add_activitysector %}
                        <a href="#" class="btn btn-sm btn-primary"
                           data-bs-toggle="modal"
                           data-bs-target="#kt_modal"
                           hx-get="{% url 'crm:create_activitysector' %}"
                           hx-target="#kt_modal_content"
                           hx-swap="innerHTML">
                           <i class="ki-duotone ki-plus fs-2"></i> {% trans 'Ajouter' %}
                        </a>
                      {% endif %}
                  </div>
                  <div id="ActivitySectorTable" class="table-responsive bg-white"
                       hx-get="{% url 'crm:list_activitysector' %}"
                       hx-trigger="refresh_table from:body, revealed"
                       hx-target="#ActivitySectorTable"
                       hx-swap="innerHTML"></div>
                  {% endif %}
              </div>

              <div class="tab-pane fade" id="tags-pane" role="tabpanel">
                  {% if perms.tags.view_tags %}
                  <div class="d-flex justify-content-between align-items-center mb-4">
                      <h3 class="mb-0 fw-bold">{% translate "Tags" %}</h3>
                      {% if perms.tags.add_tags %}
                        <a href="#" class="btn btn-sm btn-primary"
                           data-bs-toggle="modal"
                           data-bs-target="#kt_modal"
                           hx-get="{% url 'tags:create_tags' %}"
                           hx-target="#kt_modal_content"
                           hx-swap="innerHTML">
                           <i class="ki-duotone ki-plus fs-2"></i> {% trans 'Ajouter' %}
                        </a>
                      {% endif %}
                  </div>
                  <div id="TagsTable" class="table-responsive bg-white"
                       hx-get="{% url 'tags:list_tags' %}"
                       hx-trigger="refresh_table from:body, revealed"
                       hx-target="#TagsTable"
                       hx-swap="innerHTML"></div>
                  {% endif %}
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock content %}