apps/transactions/urls.py
from django.urls import path


from .views import (
    AutreTransactionDeleteBulk,
    CompanyInvoicesPaymentTable,
    CreateCompanyInvoicePaiment,
    CreateInvoiceClientPayment,
    DeleteBulkClientPayments,
    DeleteInvoicePaiement,
    DeleteLedgerEntry,
    ExportAutreTransaction,
    ExportClientPayment,
    ExportLedgerView,
    ExportStaffPayment,
    ManageAutreTransactionHtmx,
    ManageExpenseHtmx,
    ManageIncomeHtmx,
    ManageInvoicePaiementHtmx,
    ManageLedgerEntry,
    ManageStaffPaymentHtmx,
    StaffPaymentDeleteBulk,
    StaffPaymentDeleteHTMX,
    StaffPaymentView,
    StatisticClientPaymentPerMonth,
    impression_resu_autre_transaction,
    CreateCompanyQuotePayment,
    AutreTransactionView,
    ManageQuotePaiementHtmx,
    AutreTransactionDelete,
    InvoicesPaymentView,
    LedgerView,
)


app_name = "transactions"


urlpatterns = [
    # Counters



    path(
        "statistic_client_payment_per_month/",
        StatisticClientPaymentPerMonth.as_view(),
        name="statistic_client_payment_per_month",
    ),

    # 	ClientPayment
    path(
        "paiements/invoices/", InvoicesPaymentView.as_view(), name="list_clientpayment"
    ),
    # ClientPayment for company
    path(
        "paiements/invoices/create",
        ManageInvoicePaiementHtmx.as_view(),
        name="create_clientpayment",
    ),
    path(
        "paiements/quotes/create",
        ManageQuotePaiementHtmx.as_view(),
        name="create_quote_payment",
    ),
    path(
        "paiements/invoices/company/create/<int:company_pk>/",
        CreateCompanyInvoicePaiment.as_view(),
        name="create_company_clientpayment",
    ),
        path(
        "paiements/quotes/company/create/<int:company_pk>/",
        CreateCompanyQuotePayment.as_view(),
        name="create_company_quote_payment",
    ),
    
    path(
        "paiements/invoices/invoice/create/<int:bill_pk>/",
        CreateInvoiceClientPayment.as_view(),
        name="create_bill_clientpayment",
    ),
    # ClientPayment for invoice
    path(
        "paiements/bills/bill/<int:bill_pk>/",
        CreateInvoiceClientPayment.as_view(),
        name="create_invoice_clientpayment",
    ),
    path(
        "invoices-paiements/<int:pk>/update",
        ManageInvoicePaiementHtmx.as_view(),
        name="update_clientpayment",
    ),
    path(
        "invoices-paiements/<int:pk>/delete",
        DeleteInvoicePaiement.as_view(),
        name="delete_clientpayment",
    ),
    path(
        "invoices-paiements/bulk-delete",
        DeleteBulkClientPayments.as_view(),
        name="bulk_delete_clientpayment",
    ),
    path(
        "paiements/company/<int:pk>/",
        CompanyInvoicesPaymentTable.as_view(),
        name="company_invoices_payment",
    ),
    path(
        "export/invoicepayment/",
        ExportClientPayment.as_view(),
        name="export_clientpayment",
    ),
    # 	Paiement
    
    #   staff remuneration
    path(
        "remunerations_staff/",
        StaffPaymentView.as_view(),
        name="list_staffpayment",
    ),
    path(
        "remunerations_staff/create/",
        ManageStaffPaymentHtmx.as_view(),
        name="create_staffpayment",
    ),
    path(
        "remunerations_staff/update/<int:pk>",
        ManageStaffPaymentHtmx.as_view(),
        name="update_staffpayment",
    ),
    # path('remunerations_staff/create/<int:staff_member_pk>', ManageStaffPaymentHtmx.as_view(), name='create_staff_remuneration'), # Not used
    path(
        "remunerations_staff/delete/<int:pk>",
        StaffPaymentDeleteHTMX.as_view(),
        name="delete_staffpayment",
    ),
    path(
        "remunerations_staff/bulk_delete_staffpayment/",
        StaffPaymentDeleteBulk.as_view(),
        name="bulk_delete_staffpayment",
    ),
    path(
        "remunerations_staff/export_staffpayment/",
        ExportStaffPayment.as_view(),
        name="export_staffpayment",
    ),
    # Expense
    path(
        "transaction-expense/create", ManageExpenseHtmx.as_view(), name="create_expense"
    ),
    path(
        "transaction-expense/create/<str:contact_pk>",
        ManageExpenseHtmx.as_view(),
        name="create_contact_expense",
    ),
    path("transaction-income/create", ManageIncomeHtmx.as_view(), name="create_income"),
    path(
        "transaction-income/create/<str:contact_pk>",
        ManageIncomeHtmx.as_view(),
        name="create_contact_income",
    ),
    path(
        "transaction/create_autre",
        ManageAutreTransactionHtmx.as_view(),
        name="create_misctransaction",
    ),
    path(
        "transaction/update_misctransaction/<int:pk>",
        ManageAutreTransactionHtmx.as_view(),
        name="update_misctransaction",
    ),
    path(
        "transaction-income/delete/<int:pk>",
        AutreTransactionDelete.as_view(),
        name="delete_misctransaction",
    ),
    path(
        "transaction/misctransactions/list",
        AutreTransactionView.as_view(),
        name="list_misctransaction",
    ),
    path(
        "transaction/misctransactions/list/contact/<int:contact_pk>",
        AutreTransactionView.as_view(),
        name="list_contact_misctransaction",
    ),
    path(
        "transaction/export_misctransaction/",
        ExportAutreTransaction.as_view(),
        name="export_misctransaction",
    ),
    path(
        "transaction/bulk_delete_misctransaction/",
        AutreTransactionDeleteBulk.as_view(),
        name="bulk_delete_misctransaction",
    ),
    # Deleteview

    path(
        "transaction/impression_resu_autre_transaction/<int:transaction_id>",
        impression_resu_autre_transaction,
        name="impression_resu_autre_transaction",
    ),
    ####### Ledger
    path("transaction/ledger", LedgerView.as_view(), name="ledger_entry"),
    path("transaction/export_ledger", ExportLedgerView.as_view(), name="export_ledger"),
    path("transactions/ledgerentry/create/", ManageLedgerEntry.as_view(), name="create_ledgerentry"),
    path("transactions/ledgerentry/update/<int:pk>/", ManageLedgerEntry.as_view(), name="update_ledgerentry"),
    path("transactions/delete_ledgerentry/<int:pk>/", DeleteLedgerEntry.as_view(), name="delete_ledgerentry"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

# sitemaps = {
#     'terms': TermsSitemap,
#     'faq': FAQSitemap,
#     'static': StaticSitemap
# }
urlpatterns = [
    # path('markdownx/', include('markdownx.urls')),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("apps.core.urls")),
    path("", include("apps.transactions.urls")),
    path("", include("apps.crm.urls")),
    path("", include("apps.users.urls")),
    path("", include("apps.wilayas.urls")),
    path("", include("apps.leads.urls")),
    path("", include("apps.billing.urls")),
    path("", include("apps.business.urls")),
    path("", include("apps.notification.urls")),
    path("", include("apps.appointment.urls")),
    path("", include("apps.subscription.urls")),
    path("", include("apps.tags.urls")),
    
    path('tinymce/', include('tinymce.urls')),

    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
] + debug_toolbar_urls()


if settings.DEBUG:
    # import debug_toolbar
    urlpatterns += [
        path("admin/", admin.site.urls),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += path('__debug__/', include("debug_toolbar.urls")),

apps/transactions/views.py
from django.http import HttpResponse
from django.views import View
from apps.core.mixins import (
    BaseManageHtmxFormView,
    BreadcrumbMixin,
    BulkDeleteMixinHTMX,
    ChartMixin,
    DeleteMixinHTMX,
    ExportDataMixin,
)
from apps.crm.models.contact import Contact
from .forms import (
    ExpenseModelForm,
    IncomeModelForm,
    BillPaiementModelForm,
    StaffPaymentModelForm,
)
import weasyprint

from django_tables2 import SingleTableMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django_filters.views import FilterView
from .models import (
    Expense,
    Income,
    ClientPayment,
    LedgerEntry,
    StaffPayment,
    MiscTransaction,
)
from .tables import (
    ClientPaymentHTMxTable,
    LedgerEntryTable,
    StaffPaymentHTMxTable,
    AutreTransactionTableHTMxTable,
)
from .filters import (
    ClientPaymentFilter,
    LedgerEntryFilter,
    StaffPaymentsFilter,
    AutreTransactionFilter,
)
from django.db.models import Sum, F, DecimalField, Q

from django.template.loader import render_to_string
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.db.models import ExpressionWrapper

User = get_user_model()



######################### INVOICES VIEWS #########################



# tables views
class InvoicesPaymentView(
    BreadcrumbMixin, PermissionRequiredMixin, SingleTableMixin, FilterView
):
    permission_required = "transactions.view_clientpayment"
    table_class = ClientPaymentHTMxTable
    filterset_class = ClientPaymentFilter
    paginate_by = 15
    model = ClientPayment

    def get_queryset(self):
        queryset = ClientPayment.objects.select_related(
            "bill", "created_by", "updated_by"
        ).order_by("-created_at")
        filters = self.filterset_class(self.request.GET, queryset=queryset)
        return filters.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["list_url"] = self.get_queryset().model.get_list_url()
        total_payments = self.filterset.qs.aggregate(total=Sum("amount")).get(
            "total", 0
        )
        context["total"] = total_payments
        context["total_income"] = total_payments
        context["total_expense"] = 0
        context["bulk_delete_url"] = self.model.get_bulk_delete_url()
        context["create_url"] = self.get_queryset().model.get_create_url()
        context["export_url"] = self.model.get_export_url()
        context["has_perms"] = self.request.user.has_perm("transactions.add_clientpayment")
        return context

    def get_template_names(self):
        if self.request.htmx:
            template_name = "tables/table_partial.html"
        else:
            template_name = "transactions.html"
        return template_name


class CompanyInvoicesPaymentTable(InvoicesPaymentView):
    def get_queryset(self):
        queryset = super().get_queryset()
        pk = self.kwargs.get("pk")
        queryset = ClientPayment.objects.filter(
            Q(bill__lead__company__pk=pk ) | Q(client__pk=pk)
        ).order_by("-created_at")
        return queryset

    def get_table_kwargs(self):
        return {"company_pk": self.kwargs.get("pk")}


class ManageInvoicePaiementHtmx(BaseManageHtmxFormView):
    permission_required = "transactions.add_clientpayment"
    form_class = BillPaiementModelForm
    model = ClientPayment
    extra_kwargs = {"bill_type": "invoice"}
    hx_triggers = {
        "closeModal": "kt_modal",
        "refresh_table": None,
        "update_total": None,
    }

class ManageQuotePaiementHtmx(ManageInvoicePaiementHtmx):
    extra_kwargs = {"bill_type": "quote"}


class CreateCompanyInvoicePaiment(ManageInvoicePaiementHtmx):
    parent_url_kwarg = ("company_pk",)

class CreateCompanyQuotePayment(ManageInvoicePaiementHtmx):
    parent_url_kwarg = ("company_pk", )
    extra_kwargs = {"bill_type": "quote"}
    
    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs['company_pk'] = self.kwargs.get('company_pk')
    #     return kwargs


class CreateInvoiceClientPayment(ManageInvoicePaiementHtmx):
    parent_url_kwarg = ("bill_pk",)


class DeleteInvoicePaiement(DeleteMixinHTMX):
    model = ClientPayment


class DeleteBulkClientPayments(BulkDeleteMixinHTMX):
    model = ClientPayment


class ExportClientPayment(PermissionRequiredMixin, ExportDataMixin, View):
    permission_required = "transactions.view_clientpayment"
    model = ClientPayment
    fields = [
        "bill",
        "amount",
        "rest_amount",
        "notes",
        "date",
    ]



# --------------------------------------- staff-------------------------------------------------
class StaffPaymentView(
    BreadcrumbMixin, PermissionRequiredMixin, SingleTableMixin, FilterView
):
    permission_required = "transactions.view_staffpayment"
    table_class = StaffPaymentHTMxTable
    paginate_by = 15
    model = StaffPayment
    filterset_class = StaffPaymentsFilter

    def get_queryset(self):
        queryset = StaffPayment.objects.select_related(
            "staff_member", "created_by"
        ).order_by("-created_at")
        filters = self.filterset_class(self.request.GET, queryset=queryset)
        return filters.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["list_url"] = self.get_queryset().model.get_list_url()
        context["create_url"] = self.get_queryset().model.get_create_url()
        context["bulk_delete_url"] = self.model.get_bulk_delete_url()
        context["export_url"] = self.model.get_export_url()
        context["has_perms"] = self.request.user.has_perm(
            "transactions.add_staffpayment"
        )
        context["list_url"] = self.get_queryset().model.get_list_url()
        return context

    def get_template_names(self) -> list[str]:
        if self.request.htmx:
            return ["tables/table_partial.html"]
        return ["staff-transactions.html"]


class ManageStaffPaymentHtmx(BaseManageHtmxFormView):
    form_class = StaffPaymentModelForm
    model = StaffPayment
    # parent_url_kwarg = 'staff_member_pk'

    hx_triggers = {
        "closeModal": "kt_modal",
        "refresh_table": None,
        "update_total": None,
    }


class StaffPaymentDeleteHTMX(DeleteMixinHTMX):
    model = StaffPayment
    htmx_additional_event = "refresh_table"


class StaffPaymentDeleteBulk(BulkDeleteMixinHTMX):
    model = StaffPayment


class ExportStaffPayment(PermissionRequiredMixin, ExportDataMixin, View):
    permission_required = "transactions.view_staffpayment"
    model = StaffPayment
    fields = [
        "staff_member",
        "amount",
        "notes",
        "date",
    ]


# --------------------------------------- DIVERS TRANSACTION --------------------------------------------


class AutreTransactionView(
    BreadcrumbMixin, PermissionRequiredMixin, SingleTableMixin, FilterView
):
    permission_required = "transactions.view_misctransaction"
    table_class = AutreTransactionTableHTMxTable
    filterset_class = AutreTransactionFilter
    paginate_by = 20
    model = MiscTransaction

    def get_queryset(self):
        queryset = MiscTransaction.objects.select_related("contact")
        contact_pk = self.kwargs.get("contact_pk")
        if contact_pk:
            contact = get_object_or_404(Contact, pk=contact_pk)
            queryset = queryset.filter(contact=contact)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["list_url"] = self.get_queryset().model.get_list_url()
        context["bulk_delete_url"] = self.model.get_bulk_delete_url()
        context["export_url"] = self.model.get_export_url()
        filtered_qs = self.filterset.qs

        total_revenu = (
            filtered_qs.filter(transaction_type="income").aggregate(Sum("amount"))[
                "amount__sum"
            ]
            or 0
        )

        total_expense = (
            filtered_qs.filter(transaction_type="expense").aggregate(Sum("amount"))[
                "amount__sum"
            ]
            or 0
        )

        result = total_revenu - total_expense

        context["total"] = result
        context["total_income"] = total_revenu
        context["total_expense"] = total_expense

        return context

    def get_template_names(self):
        if self.request.htmx:
            template_name = "tables/table_partial.html"
        else:
            template_name = "misc-transactions.html"
        return template_name



class ManageAutreTransactionHtmx(BaseManageHtmxFormView):
    form_class = IncomeModelForm
    model = MiscTransaction

    hx_triggers = {
        "closeModal": "kt_modal",
        "refresh_table": None,
        "update_total": None,
    }


class ManageIncomeHtmx(ManageAutreTransactionHtmx):
    model = Income
    parent_url_kwarg = ("contact_pk",)


class ManageExpenseHtmx(ManageIncomeHtmx):
    model = Expense
    form_class = ExpenseModelForm


class AutreTransactionDelete(DeleteMixinHTMX):
    model = MiscTransaction
    htmx_additional_event = "refresh_table_transactions_table"


class AutreTransactionDeleteBulk(BulkDeleteMixinHTMX):
    model = MiscTransaction


class ExportAutreTransaction(PermissionRequiredMixin, ExportDataMixin, View):
    permission_required = "transactions.view_misctransaction"
    model = MiscTransaction
    fields = [
        "title",
        "contact",
        "amount",
        "notes",
        "date",
        "transaction_type",
    ]


class StatisticClientPaymentPerMonth(ChartMixin):
    model = ClientPayment
    field_to_aggregate = "invoice_remaining_amount"   # <-- add this
    permission = "transactions.can_view_chiffre_affaire"
    chart_id = "invoiceChart"
    chart_title = "Chiffre d'affaire par mois des Factures"
    date_field = "date"
    chart_type = "pie"
    aggregate_function = Sum  # ensure Sum is used

apps/transactions/templates/misc-transactions.html
{% extends "layout/base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load i18n %}
{% load render_table from django_tables2 %}

{% block content %}
<div class="d-block d-md-flex justify-content-between align-items-end mb-4">
    {% include 'snippets/_breadcrumb.html' %}
    {% block create_buttons %}

        {% if perms.transactions.add_misctransaction %}
            <div class="d-flex align-items-end gap-2">
                {% include "snippets/_export_button.html" with  modal_id="export_id" %}
                <button 
                    class="btn btn-success d-flex align-items-center shadow"
                    data-bs-toggle="modal"
                    data-bs-target="#kt_modal"
                    hx-get="{% url 'transactions:create_income' %}"
                    hx-target="#kt_modal_content"
                    hx-swap="innerHTML"
                >
                    <i class="ki-duotone ki-plus fs-4"></i>
                    <span class="fw-semibold">{% trans 'Entrée' %}</span>
                </button>
                <button 
                    class="btn btn-danger d-flex align-items-center  shadow"
                    data-bs-toggle="modal"
                    data-bs-target="#kt_modal"
                    hx-get="{% url 'transactions:create_expense' %}"
                    hx-target="#kt_modal_content"
                    hx-swap="innerHTML"
                >
                    <i class="ki-duotone ki-plus fs-4"></i>
                    <span class="fw-semibold">{% trans 'Sortie' %}</span>
                </button>
            </div>
        {% endif %}
    {% endblock create_buttons %}
</div>

{% include "snippets/toolbar.html" %}

<div id="miscTransactionTable" 
    class="table-responsive table-container"
    hx-get="{% url 'transactions:list_misctransaction' %}"
    hx-trigger="refresh_table from:body"
    hx-swap="innerHTML"
    hx-target="closest .table-responsive"
>
	{% render_table table %}
</div>

{% endblock content %}

{% block modal %}
    {% include "popups/export_modal.html" with export_url=export_url modal_id="export_id" %}


{% endblock modal %}

apps/transactions/templates/staff-transactions.html
{% extends "transactions.html" %}
{% load widget_tweaks %}
{% load render_table from django_tables2 %}
{% load static %}
{% load i18n %}





{% block create_buttons %}
    {% include "snippets/_export_button.html" with  modal_id="export_id" %}
    {% if not is_ledger_url %}
        <button 
            class="btn btn-primary d-flex align-items-center  shadow"
            data-bs-toggle="modal"
            data-bs-target="#kt_modal"
            hx-get="{{ create_url }}"
            hx-target="#kt_modal_content"
            hx-swap="innerHTML"
        >
            <i class="ki-duotone ki-plus fs-4"></i>
            <span class="fw-semibold"> {{ page_title }} </span>
        </button>
    {% endif %}
{% endblock create_buttons %}

apps/transactions/templates/transactions.html
{% extends "layout/base.html" %}
{% load widget_tweaks %}
{% load render_table from django_tables2 %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="d-block d-md-flex justify-content-between align-items-end mb-4">
    {% include 'snippets/_breadcrumb.html' %}
    {% if has_perms %}
        <div class="d-flex align-items-end gap-2">
            {% block create_buttons %}
            
                {% include "snippets/_export_button.html" with  modal_id="export_id" %}
            <button 
                class="btn btn-success d-flex align-items-center  shadow"
                data-bs-toggle="modal"
                data-bs-target="#kt_modal"
                hx-get="{% url 'transactions:create_clientpayment' %}"
                hx-target="#kt_modal_content"
                hx-swap="innerHTML"
            >
                <i class="ki-duotone ki-plus fs-4"></i>
                <span class="fw-semibold"> {% translate "Paiement Facture" %} </span>
            </button>
             <button 
                class="btn btn-primary d-flex align-items-center shadow"
                data-bs-toggle="modal"
                data-bs-target="#kt_modal"
                hx-get="{% url 'transactions:create_quote_payment' %}"
                hx-target="#kt_modal_content"
                hx-swap="innerHTML"
            >
                <i class="ki-duotone ki-plus fs-4"></i>
                <span class="fw-semibold"> {% translate "Paiement Autre" %} </span>
            </button>
            {% endblock create_buttons %}
        </div>
    {% endif %}
</div>
{% include "snippets/toolbar.html" %}

<div id="TransactionTable" 
    class="table-responsive table-container"
    hx-get="{{ list_url }}"
    hx-trigger="refresh_table from:body, load"
    hx-swap="innerHTML"
    hx-target="closest .table-responsive"
>
    {% render_table table %} 
</div>

{% endblock content %}

{% block modal %}
    {% include "popups/export_modal.html" with export_url=export_url modal_id="export_id" %}
{% endblock modal %}