apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import (
    BulkDeleteGroups,
    DeleteUser,
    UserUpdateView,
    UserCreateView,
    UserBulkDeleteView,
    add_edit_group,
    UserDetailView,
    UserListView,
    change_password,
    LoginView,
    logout_view,
    RoleListView,
    UsersPerformanceB2BView,
    UsersPerformanceB2CView,
    GroupDeleteView,
)
from django.urls import reverse_lazy

app_name = "users"

urlpatterns = [
    path("users/", UserListView.as_view(), name="list_user"),
    path(
        "users-performance-b2b/",
        UsersPerformanceB2BView.as_view(),
        name="performance_b2b_user",
    ),
    path(
        "users-performance-b2c/",
        UsersPerformanceB2CView.as_view(),
        name="performance_b2c_user",
    ),
    path("users/detail/<int:pk>", UserDetailView.as_view(), name="detail_user"),
    path("users/create/", UserCreateView.as_view(), name="create_user"),
    path("users/update/<int:pk>/", UserUpdateView.as_view(), name="update_user"),
    # path('users/create/', UserCreateView.as_view(), name="user_create_view"),
    # path('users/update/<int:pk>/', UserUpdateView.as_view(), name="update_user"),
    path("users/delete/<int:pk>/", DeleteUser.as_view(), name="delete_user"),
    path(
        "users/bulk_delete_users/",
        UserBulkDeleteView.as_view(),
        name="bulk_delete_users",
    ),
    path("users/change_password/<int:pk>/", change_password, name="change_password"),
    ###### AUTHENTICATION ##############
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
    # path('signup/', SignupView.as_view(), name="signup"),
    # path('signup_success/', SignupsuccessView.as_view(), name="signup_success"),
    ###### ROLES ##############
    path("grouplist/", RoleListView.as_view(), name="grouplist"),
    path("create_group/", add_edit_group, name="create_group"),
    path("update_group/<int:pk>/", add_edit_group, name="update_group"),
    path("roles/delete/<int:pk>/", GroupDeleteView.as_view(), name="delete_group"),
    path("roles/bulk-delete/", BulkDeleteGroups.as_view(), name="bulk_delete_groups"),
    ###### PASSWORD RESET ##############
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset_form.html",
            email_template_name="registration/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="registration/password_change_form.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

# sitemaps = {
#     'terms': TermsSitemap,
#     'faq': FAQSitemap,
#     'static': StaticSitemap
# }
urlpatterns = [
    # path('markdownx/', include('markdownx.urls')),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("apps.core.urls")),
    path("", include("apps.transactions.urls")),
    path("", include("apps.crm.urls")),
    path("", include("apps.users.urls")),
    path("", include("apps.wilayas.urls")),
    path("", include("apps.leads.urls")),
    path("", include("apps.billing.urls")),
    path("", include("apps.business.urls")),
    path("", include("apps.notification.urls")),
    path("", include("apps.appointment.urls")),
    path("", include("apps.subscription.urls")),
    path("", include("apps.tags.urls")),
    
    path('tinymce/', include('tinymce.urls')),

    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
] + debug_toolbar_urls()


if settings.DEBUG:
    # import debug_toolbar
    urlpatterns += [
        path("admin/", admin.site.urls),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += path('__debug__/', include("debug_toolbar.urls")),

apps/users/forms.py
from django.contrib.auth.forms import (
    UserCreationForm as DjangoUserCreationForm,
    UserChangeForm as DjangoUserChangeForm,
)
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UsernameField
from django.contrib.auth import authenticate
from django.contrib.auth import get_user_model

from . import models
from django.utils.translation import gettext_lazy as _

import logging

from django import forms

logger = logging.getLogger(__name__)
User = get_user_model()


class UserCreationForm(DjangoUserCreationForm, forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "email",
            "first_name",
            "last_name",
            "groups",
            "tags",
            "phone",
            "is_staff",
            "is_commercial",
            "is_active",
            "password1",
        )
        field_classes = {"email": UsernameField}

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.request = request
        if not self.request.user.is_superuser and self.request.user.has_perm(
            "users.change_user"
        ):
            self.fields.pop("is_active", None)
            self.fields.pop("is_staff", None)
            self.fields.pop("groups", None)


class UserUpdateForm(forms.ModelForm):
    class Meta(DjangoUserChangeForm.Meta):
        model = User
        fields = (
            "email",
            "first_name",
            "last_name",
            "groups",
            "tags",
            "phone",
            "is_staff",
            "is_commercial",
            "is_active",
        )

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
        if not self.request.user.is_superuser and self.request.user.has_perm(
            "users.change_user"
        ):
            self.fields.pop("is_active", None)
            self.fields.pop("is_staff", None)
            self.fields.pop("groups", None)


class ChangePasswordForm(forms.ModelForm):
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = models.User
        fields = ("password",)
        widgets = {
            # 'first_name': forms.TextInput(attrs={'class' : 'form-control' }),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")

        if password and password2:
            if password != password2:
                self.add_error(
                    "password2", _("Les mots de passe ne correspondent pas.")
                )
        return cleaned_data


class AddGroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = (
            "name",
            "permissions",
        )

    def __init__(self, *args, **kwargs):
        super(AddGroupForm, self).__init__(*args, **kwargs)
        self.fields["name"].error_messages = {
            "required": "veuillez choisir.",
            "invalid": "Custom error message for field1 is invalid.",
        }


# --------------------------------------Authentication-------------------------------------------------
class AuthenticationForm(forms.Form):  # Login Form
    email = forms.EmailField()
    password = forms.CharField(strip=False, widget=forms.PasswordInput)

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        if email is not None and password:
            self.user = authenticate(
                self.request, email=email.lower(), password=password
            )
            if self.user is None:
                raise forms.ValidationError("Invalid email/password combination.")
        logger.info("Authentication successful for email=%s", email)
        return self.cleaned_data

    def get_user(self):
        return self.user


class UsersActionForm(forms.Form):

    affect_leads = forms.IntegerField(required=False)
    is_absent = forms.BooleanField(
        label=_("Déclarer absent"),
        required=False,
    )

    def clean(self):
        cleaned_data = super().clean()
        selected_rows = self.data.getlist("selected_rows")
        if not selected_rows:
            raise forms.ValidationError(_("Veuillez séléctionné au moins une ligne."))
        return cleaned_data

apps/users/templates/accounts/group_list.html
{% extends "layout/base.html" %}

{% load render_table from django_tables2 %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="d-block d-md-flex justify-content-between align-items-end mb-4">
    {% include 'snippets/_breadcrumb.html' %}
        <div class="d-flex align-items-end gap-2">
			{% if perms.auth.add_group  %}
				<button 
					class="btn btn-primary d-flex align-items-end gap-2 shadow"
					data-bs-toggle="modal"
					data-bs-target="#kt_modal"
					hx-get="{% url 'users:create_group' %}"
					hx-target="#kt_modal_content"
					hx-swap="innerHTML"
				>
					<i class="ki-duotone ki-plus fs-4"></i>
					<span class="fw-semibold">{% trans 'Role' %}</span>
				</button>
			{% endif %}
        </div>
</div>
{% include "snippets/toolbar.html" %}

<div id="contactTable" 
    class="table-responsive table-container"
    hx-get="{% url 'users:grouplist' %}"
    hx-trigger="refresh_table from:body"
    hx-swap="innerHTML"
    hx-target="closest .table-responsive"
>
	{% render_table table %}
</div>
{% endblock content %}

apps/users/templates/accounts/login.html
{% load static %}

{% load i18n %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
		<meta charset="utf-8" />
		<meta
			name="description"
			content="La solution de gestion de gym la plus avancée développée par Octopus Consulting. Gérez vos membres, cours, et paiements facilement avec notre application intuitive et performante."
		/>
		<meta property="og:title" content="Octopus Consulting - Application de gestion de gym" />
		<meta property="og:site_name" content="Octopus Consulting" />
		<meta
			property="og:description"
			content="La solution de gestion de gym la plus avancée développée par Octopus Consulting. Gérez vos membres, cours, et paiements facilement avec notre application intuitive et performante."
		/>
		<meta
			name="keywords"
			content="gym management, gym software, Octopus Consulting, member management, course management, payment management, fitness, health, gym application, intuitive gym software, advanced gym solution"
		/>
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta property="og:locale" content="fr_FR" />
		<meta property="og:type" content="website" />
		<meta property="og:title" content="Octopus Consulting - Application de gestion de gym" />
		<meta property="og:url" content="https://octopus-consulting.com" />
		<meta property="og:site_name" content="Octopus Consulting" />
		<link rel="canonical" href="https://octopus-consulting.com" />
		<link rel="shortcut icon" href="{% static 'images/logo.png' %}" />

		<link href="{% static 'fonts/inter.css' %}" rel="stylesheet" type="text/css" />

		<link href="{% static 'plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />

		<script src="{% static 'js/htmx.min.js' %}"></script>
		<script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
	<title>{% translate "Page de connexion" %}</title>
</head>
<body>
	<div class="d-flex flex-column flex-root" id="kt_app_root">
		<div class="d-flex flex-column flex-lg-row flex-column-fluid">
			<div class="d-flex flex-column flex-lg-row-fluid w-lg-50 p-10 order-2 order-lg-1">
				<div class="d-flex flex-center flex-column flex-lg-row-fluid">
					<div class="w-lg-500px p-10">
						{% if messages %}
							<div class="messages mb-5">
								{% for message in messages %}
									<div class="alert alert-{% if message.tags %}{{ message.tags }}{% else %}danger{% endif %} p-4 mb-3 d-flex align-items-center">
										<i class="fas fa-exclamation-circle me-2"></i>
										<span>{{ message }}</span>
										<button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
									</div>
								{% endfor %}
							</div>
						{% endif %}
						{% csrf_token %}
						<form class="form w-100 fv-plugins-bootstrap5 fv-plugins-framework" method="post" action=".">
							{% csrf_token %}
							<div class="text-center mb-11">
								<h1 class="text-light-secondary  ">{% translate 'Connectez vous pour Continuer' %}</h1>
							</div>
							<div class="fv-row mb-8 fv-plugins-icon-container">
								{% render_field form.email class='form-control bg-transparent' placeholder="Email" id="loginInput" %}
								<div class="fv-plugins-message-container invalid-feedback"></div>
							</div>
							<div class="fv-row mb-8 fv-plugins-icon-container">
								{% render_field form.password class='form-control bg-transparent' placeholder="Password" %}
								<div class="fv-plugins-message-container invalid-feedback"></div>
							</div>
							<div class="form-check form-switch form-switch-sm form-check-custom form-check-solid">
								<input type="checkbox" id="rememberMe" name="remember_me" class="form-check-input" checked>
								<label class="form-check-label" for="rememberMe">{% translate 'Resté connecté' %}</label>
							</div>
							<div class="d-flex justify-content-end mb-3">
								<a href="{% url 'users:password_reset' %}" class="link-primary">{% translate 'Forgot Password?' %}</a>
							</div>
							<div class="d-grid mb-10">
								<button type="submit" id="submitButton" class="btn btn-primary">
									<span class="indicator-label">{% translate 'Login' %}</span>
									<span class="indicator-progress">Please wait...
										<span class="spinner-border spinner-border-sm align-middle ms-2"></span>
									</span>
								</button>
							</div>
						</form>
					</div>
				</div>
				<div class="d-flex flex-center flex-wrap px-5">
					<div class="d-flex fw-semibold text-primary fs-base">
					
					</div>
				</div>
			</div>
			<div class="d-flex flex-lg-row-fluid w-lg-50 bgi-size-cover bgi-position-center order-1 order-lg-3" style="background-image: url({% static 'images/logos/school.jpeg' %})">
			
			</div>
		</div>
	</div>
	
</body>
</html>

apps/users/templates/accounts/signup.html
{% load static %}
{% block content %}
{% block title %}
<title>Signup</title>
{% endblock %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'vendors/iconfonts/font-awesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.addons.css' %}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'landing/images/logos/favicon.png' %}" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth">
          <div class="row w-100">
            <div class="col-lg-4 mx-auto">
              <div class="auth-form-light text-left p-5">
                <div class="brand-logo d-flex justify-content-center">
                  <img src="{% static 'images/logo.png' %}" alt="logo">
                </div>
                <h6 class="font-weight-light">créer un compte</h6>
                <form class="pt-3" action="" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    {{ form.email.label_tag }}
                    <input type="email" class="form-control {% if form.email.errors %}  is-invalid{% endif %}" id="id_email" name="email" placeholder="Votre email" value="{{ form.email.value|default:"" }}" > {% if form.email.errors %}
                      <div class="invalid-feedback">
                          {{ form.email.errors }}
                        </div>
                        {% endif %}
                  </div>
                  <div class="form-group">
                    {{ form.password1.label_tag }}
                      <input type="password" class="form-control {% if form.password1.errors %}  is-invalid{% endif %}" id="id_password1" name="password1" value="{{ form.password1.value|default:"" }}"> {% if form.password1.errors %}
                        <div class="invalid-feedback">
                          {{ form.password1.errors }}
                        </div>
                        {% endif %}
                  </div>
                  <div class="form-group">
                    {{ form.password2.label_tag }}
                      <input type="password" class="form-control{% if form.password2.errors %}  is-invalid{% endif %}" id="id_password2" name="password2" value="{{ form.password2.value|default:"" }}"> {% if form.password2.errors %}
                        <div class="invalid-feedback">
                           {{ form.password2.errors }}
                         </div>
                        {% endif %}
                    </div>
                  <div class="mb-4">
                  </div>
                  <div class="mt-3">
                    <button type="submit" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">S'INSCRIRE</button>
                  </div>
                  <div class="text-center mt-4 font-weight-light">
                    {% comment %} Vous avez déjà un compte? <a href="{% url 'accounts:login' %}" class="text-primary">connectez-vous</a> {% endcomment %}
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->


   <!-- plugins:js -->
   <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
   <script src="{% static 'vendors/js/vendor.bundle.addons.js' %}"></script>
   <!-- endinject -->
   <!-- inject:js -->
   <script src="{% static 'js/off-canvas.js' %}"></script>
   <script src="{% static 'js/hoverable-collapse.js' %}"></script>
   <script src="{% static 'js/misc.js' %}"></script>
   <script src="{% static 'js/settings.js' %}"></script>
   <script src="{% static 'js/todolist.js' %}"></script>
   <!-- endinject -->
 </body>


{% endblock content %}

apps/users/templates/accounts/signup_message.html
{% load static %}
{% block content %}
{% block title %}
<title>Signup</title>
{% endblock %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'vendors/iconfonts/font-awesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.addons.css' %}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{% static 'landing/images/logos/favicon.png' %}" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth">
          <div class="row w-100">
            <div class="col-lg-4 mx-auto">
              <div class="auth-form-light text-left p-5">
                <div class="brand-logo d-flex justify-content-center">
                  <img src="{% static 'images/logo.png' %}" alt="logo" >
                </div>
                <h4>vous avez créer un compte avec succès</h4>
                <h6 class="font-weight-light">Malheureusement, vous ne pouvez pas vous connecter.</h6>
                <h6 class="font-weight-light">Veuillez patienter pendant que des privilèges vous sont accordés.</h6>

              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->


   <!-- plugins:js -->
   <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
   <script src="{% static 'vendors/js/vendor.bundle.addons.js' %}"></script>
   <!-- endinject -->
   <!-- inject:js -->
   <script src="{% static 'js/off-canvas.js' %}"></script>
   <script src="{% static 'js/hoverable-collapse.js' %}"></script>
   <script src="{% static 'js/misc.js' %}"></script>
   <script src="{% static 'js/settings.js' %}"></script>
   <script src="{% static 'js/todolist.js' %}"></script>
   <!-- endinject -->
 </body>


{% endblock content %}

apps/users/templates/accounts/user_list.html
{% extends "layout/base.html" %}
{% load static %}
{% load i18n %}
{% load render_table from django_tables2 %}

{% block content %}
<div class="d-block d-md-flex justify-content-between align-items-end mb-4">
    {% include 'snippets/_breadcrumb.html' %}
	<div class="d-flex align-items-end gap-2">
		{% if perms.users.add_user %}
			<button 
				class="btn btn-primary d-flex align-items-end gap-2 shadow"
				data-bs-toggle="modal"
				data-bs-target="#kt_modal"
				hx-get="{% url 'users:create_user' %}"
				hx-target="#kt_modal_content"
				hx-swap="innerHTML"
			>
				<i class="ki-duotone ki-plus fs-4"></i>
				<span class="fw-semibold">{% trans 'Utilisateur' %}</span>
			</button>
		{% endif %}
	</div>
</div>
<ul class="nav nav-stretch nav-line-tabs nav-line-tabs-2x text-uppercase border-transparent fs-5 fw-bold">
    <li class="nav-item mt-2" role="presentation">
        <a class="nav-link pb-4 active d-flex align-items-center gap-2"
            data-bs-toggle="tab"
            role="tab"
            href="#kt_tab_list_user"
            hx-get="{% url 'users:list_user' %}"
			hx-trigger="refresh_table from:body, click"
			hx-swap="innerHTML"
			hx-target="#kt_tab_list_user div.table-responsive"
        >
            <i class="ki-outline ki-bank fs-2"></i>
            {% trans 'Liste des utilisateurs' %}
        </a>
    </li>
    <li class="nav-item mt-2" role="presentation">
        <a class="nav-link pb-4 d-flex align-items-center gap-2"
            data-bs-toggle="tab"
            role="tab"
            href="#kt_tab_performance_b2b"
            hx-get="{% url 'users:performance_b2b_user' %}"
			hx-swap="innerHTML"
            hx-trigger="refresh_table from:body, click"
            hx-target="#kt_tab_performance_b2b div.table-responsive" 
        >
            <i class="ki-outline ki-profile-user fs-2"></i>
            {% trans 'Performance B2B' %}
        </a>
    </li>
	<li class="nav-item mt-2" role="presentation">
        <a class="nav-link pb-4 d-flex align-items-center gap-2"
            data-bs-toggle="tab"
            role="tab"
            href="#kt_tab_performance_b2c"
            hx-get="{% url 'users:performance_b2c_user' %}"
			hx-swap="innerHTML"
            hx-trigger="refresh_table from:body, click"
            hx-target="#kt_tab_performance_b2c div.table-responsive" 
        >
            <i class="ki-outline ki-profile-user fs-2"></i>
            {% trans 'Performance B2C' %}
        </a>
    </li>
</ul>



{% include "snippets/toolbar.html" %}
<div class="d-flex flex-column flex-lg-row">
    <div class="flex-lg-row-fluid ">
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade active show" id="kt_tab_list_user" role="tabpanel">
                <div class="card-body pt-0 table-responsive table-container" id="tableContainer">
                    {% render_table table %}
                </div>
            </div>	
            <div class="tab-pane fade" id="kt_tab_performance_b2b" role="tabpanel">
                <div class="card-body pt-0 table-responsive table-container" id="tableContainer">
                </div>
            </div>
            <div class="tab-pane fade" id="kt_tab_performance_b2c" role="tabpanel">
                <div class="card-body pt-0 table-responsive table-container" id="tableContainer">
                </div>
            </div>						
        </div>
    </div>
</div>

{% endblock content %}