apps/appointment/urls.py
from django.urls import path
from apps.appointment.views import (
    AppointmentListView,
    DeleteAppointment,
    DeleteBulkAppointment,
    ManageLeadB2bAppointmentHtmx,
    AppointmentCalendarView,
    ManageLeadB2cAppointmentHtmx,
    UserAppointmentCalendar,
)

app_name = "appointment"


urlpatterns = [
    path("appointment/list/", AppointmentListView.as_view(), name="list_appointment"),
    path(
        "appointment/appointment_calendar/",
        AppointmentCalendarView.as_view(),
        name="appointment_calendar",
    ),
    ##### user appointment management
    path(
        "appointment/appointment_calendar/user/<int:pk>/",
        UserAppointmentCalendar.as_view(),
        name="user_appointment_calendar",
    ),
    path(
        "appointment/create/leadb2b/<int:lead_b2b_pk>/",
        ManageLeadB2bAppointmentHtmx.as_view(),
        name="create_lead_b2b_appointment",
    ),
    path(
        "appointment/create/leadb2c/<int:lead_b2c_pk>/",
        ManageLeadB2cAppointmentHtmx.as_view(),
        name="create_lead_b2c_appointment",
    ),
    path(
        "appointment/create/",
        ManageLeadB2bAppointmentHtmx.as_view(),
        name="create_appointment",
    ),
    path(
        "appointment/update/<int:pk>/",
        ManageLeadB2bAppointmentHtmx.as_view(),
        name="update_appointment",
    ),
    path(
        "appointment/delete/<int:pk>/",
        DeleteAppointment.as_view(),
        name="delete_appointment",
    ),
    path(
        "appointment/bulk_delete/",
        DeleteBulkAppointment.as_view(),
        name="bulk_delete_appointment",
    ),
    # path('appointment/detail/<int:pk>/', AppointmentDetailView.as_view(), name='detail_appointment'),
]

apps/core/urls.py
from django.urls import path
from .views import (
                    IndexView,
                    ConfigugrationView,
                    StatisticsView,
                    TaxListView,
                    ManageTaxHtmx,
                    TaxDeleteHTMX,
                    LeadSourceListView,
                    ManageLeadSourceHtmx,
                    LeadSourceDeleteHTMX,
                    PotentialListView,
                    ManagePotentialHtmx,
                    PotentialDeleteHTMX,
                    set_language,
                )


app_name = "core"


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("configuration", ConfigugrationView.as_view(), name="configuration"),
    path("set_language/<str:language>/", set_language, name="set_language"),
    path("statistics/", StatisticsView.as_view(), name="statistics"),
    # # tax---------------------------------------------------------------
    path("taxes/", TaxListView.as_view(), name="list_tax"),
    path("taxes/create", ManageTaxHtmx.as_view(), name="create_tax"),
    path("taxes/update/<int:pk>", ManageTaxHtmx.as_view(), name="update_tax"),
    path("taxes/delete/<int:pk>", TaxDeleteHTMX.as_view(), name="delete_tax"),
    path("source_leads/", LeadSourceListView.as_view(), name="list_leadsource"),
    path(
        "source_leads/create/",
        ManageLeadSourceHtmx.as_view(),
        name="create_leadsource",
    ),
    path(
        "source_leads/update/<int:pk>",
        ManageLeadSourceHtmx.as_view(),
        name="update_leadsource",
    ),
    path(
        "source_leads/delete/<int:pk>",
        LeadSourceDeleteHTMX.as_view(),
        name="delete_leadsource",
    ),
    # # Potentiel---------------------------------------------------------------
    path("potentials/", PotentialListView.as_view(), name="list_potential"),
    path("potentials/create", ManagePotentialHtmx.as_view(), name="create_potential"),
    path(
        "potentials/update/<int:pk>",
        ManagePotentialHtmx.as_view(),
        name="update_potential",
    ),
    path(
        "potentials/delete/<int:pk>",
        PotentialDeleteHTMX.as_view(),
        name="delete_potential",
    ),
]

apps/notification/urls.py
from django.urls import path
from apps.notification.views import notification_drawer, mark_notification_as_read


app_name = "notification"


urlpatterns = [
    #### notification drawer
    path("notification/drawer/", notification_drawer, name="notification_drawer"),
    path(
        "notification/read/<int:notification_id>/",
        mark_notification_as_read,
        name="mark_notification_as_read",
    ),
]

apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import (
    BulkDeleteGroups,
    DeleteUser,
    UserUpdateView,
    UserCreateView,
    UserBulkDeleteView,
    add_edit_group,
    UserDetailView,
    UserListView,
    change_password,
    LoginView,
    logout_view,
    RoleListView,
    UsersPerformanceB2BView,
    UsersPerformanceB2CView,
    GroupDeleteView,
)
from django.urls import reverse_lazy

app_name = "users"

urlpatterns = [
    path("users/", UserListView.as_view(), name="list_user"),
    path(
        "users-performance-b2b/",
        UsersPerformanceB2BView.as_view(),
        name="performance_b2b_user",
    ),
    path(
        "users-performance-b2c/",
        UsersPerformanceB2CView.as_view(),
        name="performance_b2c_user",
    ),
    path("users/detail/<int:pk>", UserDetailView.as_view(), name="detail_user"),
    path("users/create/", UserCreateView.as_view(), name="create_user"),
    path("users/update/<int:pk>/", UserUpdateView.as_view(), name="update_user"),
    # path('users/create/', UserCreateView.as_view(), name="user_create_view"),
    # path('users/update/<int:pk>/', UserUpdateView.as_view(), name="update_user"),
    path("users/delete/<int:pk>/", DeleteUser.as_view(), name="delete_user"),
    path(
        "users/bulk_delete_users/",
        UserBulkDeleteView.as_view(),
        name="bulk_delete_users",
    ),
    path("users/change_password/<int:pk>/", change_password, name="change_password"),
    ###### AUTHENTICATION ##############
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
    # path('signup/', SignupView.as_view(), name="signup"),
    # path('signup_success/', SignupsuccessView.as_view(), name="signup_success"),
    ###### ROLES ##############
    path("grouplist/", RoleListView.as_view(), name="grouplist"),
    path("create_group/", add_edit_group, name="create_group"),
    path("update_group/<int:pk>/", add_edit_group, name="update_group"),
    path("roles/delete/<int:pk>/", GroupDeleteView.as_view(), name="delete_group"),
    path("roles/bulk-delete/", BulkDeleteGroups.as_view(), name="bulk_delete_groups"),
    ###### PASSWORD RESET ##############
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset_form.html",
            email_template_name="registration/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="registration/password_change_form.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

# sitemaps = {
#     'terms': TermsSitemap,
#     'faq': FAQSitemap,
#     'static': StaticSitemap
# }
urlpatterns = [
    # path('markdownx/', include('markdownx.urls')),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("apps.core.urls")),
    path("", include("apps.transactions.urls")),
    path("", include("apps.crm.urls")),
    path("", include("apps.users.urls")),
    path("", include("apps.wilayas.urls")),
    path("", include("apps.leads.urls")),
    path("", include("apps.billing.urls")),
    path("", include("apps.business.urls")),
    path("", include("apps.notification.urls")),
    path("", include("apps.appointment.urls")),
    path("", include("apps.subscription.urls")),
    path("", include("apps.tags.urls")),
    
    path('tinymce/', include('tinymce.urls')),

    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
] + debug_toolbar_urls()


if settings.DEBUG:
    # import debug_toolbar
    urlpatterns += [
        path("admin/", admin.site.urls),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += path('__debug__/', include("debug_toolbar.urls")),

templates/snippets/_actions_menu.html
{% load static %}
{% load widget_tweaks %}
{% load i18n %}

<div class="ms-2" x-data="{ action: 'uPrice' }">
	<a href="#" class="btn btn-info d-flex align-items-center gap-2" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
		<i class="ki-outline ki-setting-4 fs-2x"></i>
		{% translate 'Actions' %}
	</a>
	<div class="menu menu-sub menu-sub-dropdown w-250px w-md-300px p-0" data-kt-menu="true" id="kt_menu_633f0992a4adf">
		<div class="border-bottom px-4 py-3 bg-light d-flex justify-content-between align-items-center">
			<span class="fw-semibold text-danger">{% translate "Delete selected" %}</span>
			<button 
				type="button"
				class="btn btn-icon btn-light-danger me-2 hover-rotate-start"
				data-bs-toggle="modal" 
				data-bs-target="#kt_modal"
				hx-get="{{ bulk_delete_url }}"
				hx-target="#kt_modal_content"
				hx-include="[name='selected_rows']"
				hx-swap="innerHTML"
				title="{% translate 'Delete selected' %}"
			>
				<i class="ki-outline ki-trash fs-2x"></i>
			</button>
		</div>

		{% for action in bulk_actions %}
			<div class="border-bottom px-4 py-3 bg-light d-flex justify-content-between align-items-center ">
			<span class="fw-semibold text-{{ action.class_color }}">{{ action.label }}</span>
				<button
					type="button"
					class="btn btn-icon btn-light-{{ action.class_color }} me-2 hover-rotate-start"
					{% if action.modal_action %}
						data-bs-toggle="modal" 
						data-bs-target="#kt_modal"
						hx-target="#kt_modal_content"
						hx-swap="innerHTML"
					{% endif %}
					hx-{{ action.method }}="{{ action.url }}"
					hx-include="[name='selected_rows']"
					title="{{ action.label }}"
				>
					<i class="{{ action.icon }} fs-2x"></i>
				</button>
			</div>
		{% endfor %}
	</div>
</div>

templates/snippets/_breadcrumb.html
{% load i18n %}
<div class="page-title d-flex flex-column justify-content-center flex-wrap m-3">
    <h1 class="page-heading text-capitalize d-flex text-gray fw-bold fs-3 flex-column justify-content-center my-0">{{ title }} </h1>
    <ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1">
        <li class="breadcrumb-item text-muted">
            <a href="{% url 'core:index' %}" class="text-muted text-hover-primary">{% translate 'Home' %}</a>
        </li>
        <li class="breadcrumb-item">
            <span class="bullet bg-gray-400 w-5px h-2px"></span>
        </li>
        {% if parent_page %}
            <li class="breadcrumb-item text-muted"> <a href="{{ parent_url }}" class="text-muted text-hover-primary">{{ parent_page }}</a></li>
            <li class="breadcrumb-item">
                <span class="bullet bg-gray-400 w-5px h-2px"></span>
            </li>
        {% endif %}
        <li class="breadcrumb-item text-muted text-capitalize">{{ page_title }}</li>
    </ul>
</div>

templates/snippets/_create_form.html
{% load i18n %}
{% load widget_tweaks %}
{% load custom_filters %}

<div class="modal-header">
    <h3 class="modal-title">   
        {% if form.instance.id %}
            {{ form_verbose_name|capfirst }} N° {{ form.instance.id }} — {% translate "Edit" %}
        {% else %}
            {% translate "Add" %} {{ form_verbose_name|capfirst }}
        {% endif %}
    </h3>
    <!--begin::Close-->
    <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
        <i class="ki-duotone ki-cross fs-1">
            <span class="path1"></span>
            <span class="path2"></span>
        </i>
    </div>
    <!--end::Close-->
</div>

<div class="modal-body scroll-y mx-5 mx-xl-5">
    <form 
        {% comment %} # TODO check this include reload_page it is firing a console errror often {% endcomment %}
        hx-post="{% if form.instance.id %} {{ update_url }} {% else %} {{ create_url }} {% endif %}" 
        hx-target="#kt_modal_content" 
        hx-include="[name='reload_page']" 
        hx-swap="innerHTML" 
        {{ form.attrs }}
        enctype="multipart/form-data"
    >
        {% csrf_token %}
    
        {% include 'forms/horizental-form.html' with margin_class="mb-4" %}
        {% if formsets %}
            {% for formset_name, formset in formsets.items %}
                {% include 'forms/horizontal-formset.html' with formset=formset container_id=formset.prefix|add:"_container" formset_name=formset_name prefix=formset.prefix %}
            {% endfor %}
        {% endif %}

        <div class="modal-footer flex-center pb-0">
            <button type="button" class="btn btn-light" data-bs-dismiss="modal">{% translate 'Close' %}</button>
            {% if form.instance.id %}
                <button 
                    type="button" 
                    class="btn btn-danger" 
                    data-bs-toggle="modal"
                    data-bs-target="#delete_modal"
                    hx-get="{{ form.instance.get_delete_url }}"   
                    hx-target="#delete_modal_body" 
                    hx-swap="innerHTML"
                >
                    {% translate 'Delete' %}
                </button>
            {% endif %}
            {% include 'snippets/_submit_button.html' %}
        </div>
    </form>
    {% if form.instance.id %}
        <form action="{{ form.instance.get_delete_url }}" method="post" id="deleteSlideForm">
            {% csrf_token %}
        </form> 
    {% endif %}
</div>




{% if formsets %}
    {% for formset_name, formset in formsets.items %}
        {% include 'snippets/formset.html' with 
            prefix=formset.prefix 
            container_id=formset.prefix|add:"_container"
            add_button_id="addButton_"|add:formset.prefix
            remove_form="remove-item" 
            form_item_class="item-form" 
            select2_item_class="form-select" 
        %}
    {% endfor %}
{% endif %}   



<script>
    $('[data-control="select2"]').select2({
        dropdownParent: $('#kt_modal_content')
    });
</script>

templates/snippets/_drawers.html
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        {% comment %} render content {% endcomment %}
    </div>
</div>

templates/snippets/_export_button.html
{% load static %}

<button type="button" class="btn btn-sm btn-flex bg-body btn-color-gray-700 btn-active-color-primary fw-bold" 
        data-bs-toggle="modal" 
        data-bs-target="#kt_subscriptions_export_modal{{ modal_id }}">
        <i class="ki-outline ki-exit-down fs-2x text-dark">
        </i>
    {% translate 'Export' %}
</button>

templates/snippets/_filters.html
{% load i18n %}
<div class="d-flex align-items-center gap-3 flex-wrap mb-0">
	<a href="#" class="btn btn-light-primary d-flex align-items-center gap-2" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
			<i class="ki-outline ki-filter-search fs-2x"></i>
			{% translate 'Filters' %}
		</a>
	<div id="filter_menu" class="menu menu-sub menu-sub-dropdown w-300px w-md-325px" data-kt-menu="true" id="kt-toolbar-filter">
		<div class="px-7 py-5">
			<div class="fs-4 text-gray-900 fw-bold">{% translate "Filter Options" %}</div>
		</div>
		<div class="separator border-gray-200"></div>
		<div class="px-7 py-5">
			{% include 'forms/vertical-form.html' with margin_class="mb-4" form=filter.form filter_menu="true" %}
			<div class="d-flex justify-content-end">
				<button type="reset" class="btn btn-light btn-active-light-primary me-2" data-kt-menu-dismiss="false" data-kt-customer-table-filter="reset">{% translate "Reset" %}</button>
				<button type="submit" class="btn btn-primary" data-kt-menu-dismiss="true" data-kt-customer-table-filter="filter">{% translate "Apply" %}</button>
			</div>
		</div>
	</div>
</div>

	

templates/snippets/_import_button.html
{% load static %}
<button class="btn btn-sm btn-flex bg-body btn-color-gray-700 btn-active-color-primary fw-bold" 
        type="button"        
        data-bs-toggle="modal" 
        data-bs-target="#kt__import_modal{{modal_id}}">
        <i class="ki-outline ki-exit-up fs-2x text-dark"></i>
        {% translate 'Import' %}
</button>

templates/snippets/_message.html
{% load i18n %}
<script type="text/javascript">
	window.addEventListener("DOMContentLoaded", (e) => {
		{% if messages %}
			{% for message in messages %}
				{% if 'toastr' in message.tags %}
					{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
						toastr.error('{{ message }}')
					{% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
						toastr.warning('{{ message }}')
					{% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
						toastr.info('{{ message }}')
					{% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
						toastr.success('{{ message }}')
					{% else %}
						toastr.error('{% trans "Contact support. Unknown error" %} {{ message }}')
					{% endif %}
				{% endif %}
			{% endfor %}
		{% endif %}
	});
</script>



<div data-toast-container class="toast-container position-fixed top-0 end-0 p-3">
	<div data-toast-template class="toast align-items-center border-0 text-white " role="alert" aria-live="assertive" aria-atomic="true">
		<div class="d-flex">
			<div data-toast-body class="toast-body"></div>
			<button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
		</div>
	</div>
</div>

templates/snippets/appointment_calender.html
<div class="card h-md-100">
    <div class="card-header border-0 pt-5">
        <h3 class="card-title align-items-start flex-column">
            <span class="card-label fw-bold text-gray-900">Rendez-vous aujourd'hui</span>
            <span class="text-muted mt-1 fw-semibold fs-7">Total {{ appointments|length }} rendez-vous</span>
        </h3>
        {% comment %} <div class="card-toolbar">
            <a href="#" class="btn btn-sm btn-light">Report Center</a>
        </div> {% endcomment %}
    </div>
    <div class="card-body pt-7 px-0">
        <ul class="nav nav-stretch nav-pills nav-pills-custom nav-pills-active-custom d-flex justify-content-between mb-8 px-5">
            {% for day in days %}
                <li class="nav-item p-0 ms-0">
                    <a class="nav-link btn d-flex flex-column flex-center rounded-pill min-w-45px py-4 px-3 btn-active-danger {% if forloop.first %}active{% endif %}" 
                       data-bs-toggle="tab" 
                       href="#kt_timeline_widget_3_tab_content_{{ forloop.counter }}">
                        <span class="fs-7 fw-semibold">{{ day|date:"D" }}</span>
                        <span class="fs-6 fw-bold">{{ day|date:"d" }}</span>
                    </a>
                </li>
            {% endfor %}
        </ul>
        <div class="tab-content mb-2 px-9">
            {% for day in days %}
                <div class="tab-pane fade {% if forloop.first %}show active{% endif %} overflow-y-auto" 
                        id="kt_timeline_widget_3_tab_content_{{ forloop.counter }}"
                        style="max-height: 400px;">
                        {% for appointment in appointments %}
                            {% if appointment.date.date == day %}
                                <div class="d-flex align-items-center mb-6 p-4 rounded shadow-sm bg-light-hover transition">
                                    <!-- State Bullet -->
                                    <span data-kt-element="bullet"
                                          class="bullet bullet-vertical d-flex align-items-center min-h-70px mh-100 me-4 bg-{{ appointment.get_state_color }} rounded-circle shadow-sm"></span>
                                    <!-- Appointment Details -->
                                    <div class="flex-grow-1 me-5">
                                        <div class="d-flex align-items-center mb-1">
                                            <span class="text-gray-900 fw-bold fs-4">{{ appointment.date|date:"H:i" }}</span>
                                            <span class="text-gray-500 fw-semibold fs-7 ms-2">{{ appointment.date|date:"A" }}</span>
                                            {% if appointment.state %}
                                                <span class="badge badge-outline badge-{{ appointment.get_state_color }} fs-5 ms-3 px-3 py-1 rounded-pill">
                                                    {{ appointment.get_state_display }}
                                                </span>
                                            {% endif %}
                                        </div>
                                        <div class="text-gray-700 fw-semibold fs-6 mb-2">{{ appointment.subject }}</div>
                                        <div class="d-flex flex-wrap align-items-center gap-2 mt-2">
                                            {% if appointment.b2b_lead %}
                                                <span class="badge badge-light-primary px-2 py-1 rounded-pill d-flex align-items-center">
                                                    <i class="bi bi-briefcase me-1"></i>
                                                    <span>Opportunité:</span>
                                                    <a href="#" class="text-primary fw-semibold text-decoration-underline ms-1">{{ appointment.b2b_lead }}</a>
                                                    {% if appointment.b2b_lead.company %}
                                                        <span class="ms-1 text-muted">({{ appointment.b2b_lead.company }})</span>
                                                    {% endif %}
                                                </span>
                                            {% endif %}
                                            {% if appointment.b2c_lead %}
                                                <span class="badge badge-light-primary px-2 py-1 rounded-pill d-flex align-items-center">
                                                    <i class="bi bi-person-badge me-1"></i>
                                                    <span>Opportunité:</span>
                                                    <a href="#" class="text-primary fw-semibold text-decoration-underline ms-1">{{ appointment.b2c_lead }}</a>
                                                    {% if appointment.b2c_lead.contact %}
                                                        <span class="ms-1 text-muted">({{ appointment.b2c_lead.contact }})</span>
                                                    {% endif %}
                                                    {% if appointment.b2c_lead.company %}
                                                        <span class="ms-1 text-muted">({{ appointment.b2c_lead.company }})</span>
                                                    {% endif %}
                                                </span>
                                            {% endif %}
                                            {% if appointment.users.exists %}
                                                <span class="badge badge-light-info px-2 py-1 rounded-pill d-flex align-items-center">
                                                    <i class="bi bi-people me-1"></i>
                                                    <span>Participants:</span>
                                                    {% for user in appointment.users.all %}
                                                        <a href="{% url 'users:detail_user' user.pk %}" class="text-info fw-semibold text-decoration-underline ms-1">{{ user.get_full_name|default:user.username }}</a>{% if not forloop.last %}, {% endif %}
                                                    {% endfor %}
                                                </span>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <!-- Edit Button -->
                                    <a class="btn btn-icon btn-light btn-sm ms-3"
                                       hx-get="{% url 'appointment:update_appointment' appointment.pk %}"
                                       data-bs-toggle="modal"
                                       data-bs-target="#kt_modal"
                                       data-bs-placement="right"
                                       data-bs-toggle="tooltip"
                                       hx-target="#kt_modal_content"
                                       hx-swap="innerHTML"
                                       title="{% translate 'modifier' %}">
                                        <i class="ki-duotone ki-notepad-edit fs-2x">
                                            <span class="path1"></span>
                                            <span class="path2"></span>
                                        </i>
                                    </a>
                                </div>
                            {% endif %}
                        {% endfor %}
                </div>
            {% endfor %}
        </div>
       
    </div>
</div>

templates/snippets/htmx_delete_modal.html
{% load i18n %}

<div class="modal-content">
    <div class="modal-header">
        <h3 class="modal-title">{% trans 'Suppression'%} {{object}} </h3>
        <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
            <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
        </div>
    </div>
    <div class="modal-body">
        <p class="h4">{% trans 'Etes-vous sûr de vouloir supprimer de : ' %} {{object}}</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-bs-dismiss="modal">{% trans 'Annulé' %}</button>
        <form hx-post="{{object.get_delete_url}}" hx-include="[name='reload_page']" method="post">
            {% csrf_token %}
            <button type="submit" id="submitButton" class="btn btn-danger">
                <span class="indicator-label">
                    {% translate 'Supprimer' %}
                </span>
                <span class="indicator-progress">
                    {% translate 'Patientez...' %} <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                </span>
            </button>
        </form>
    </div>
</div>

templates/snippets/notification_drawer.html
<div   
        class="container my-4"
        hx-get="{% url 'notification:notification_drawer' %}"
        hx-trigger="refresh_list from:body"
        hx-swap="innerHTML"
        style="max-width: 400px;"
    >
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2 class="fw-bold mb-0">
            <i class="bi bi-bell-fill text-primary me-2 fs-2x"></i>Notifications
        </h2>
        {% if notifications %}
            <span class="badge bg-primary-subtle text-primary-emphasis px-3 py-2 rounded-pill fs-6">
                {{ notifications|length }} nouvelles
            </span>
        {% endif %}
    </div>
    <div class="d-flex flex-column gap-4 mx-auto" >
        <!-- Notifications Drawer -->
        {% for notification in notifications %}
            <div class="card border-0 shadow-sm position-relative overflow-hidden notification-card bg-primary-subtle">
                <span class="position-absolute top-0 end-0 m-2" style="z-index:2;">
                    <a class="btn btn-link text-danger p-0"
                       hx-get="{% url 'notification:mark_notification_as_read' notification.id %}"
                       hx-swap="innerHTML">
                        <i class="ki-outline ki-cross-circle fs-2 text-danger"></i>
                    </a>
                </span>
                <div class="card-body d-flex align-items-center gap-3 p-3">
                    <!-- Avatar / Icon -->
                    <div class="flex-shrink-0">
                           <i class="ki-solid ki-notification-bing fs-2x text-warning">
                            </i>
                    </div>
                    <!-- Content -->
                    <div class="flex-grow-1">
                        <div class="fw-semibold text-primary-emphasis mb-1" style="font-size: 1.06rem;">
                            {{ notification.message }}
                        </div>
                        <div class="d-flex gap-2 small text-muted align-items-center">
                            <span>
                                <i class="bi bi-person me-1"></i>{{ notification.recipient }}
                            </span>
                            <span>
                                <i class="bi bi-clock me-1"></i>
                                {{ notification.date|date:"d M Y" }}
                            </span>
                        </div>
                    </div>
                </div>
                <a href="{{ notification.link }}" class="stretched-link"></a>
            </div>
        {% empty %}
            <div class="alert alert-secondary text-center rounded-3 py-5">
                <i class="bi bi-bell fs-1 mb-3 text-primary mb-5"></i><br>
                <h2 class="fw-bold mt-6">Aucune notification.</h2>
            </div>
        {% endfor %}
    </div>
</div>